# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/aakanksha54/app-py.4422fc3b-af58-41e2-b86f-adbdc7bb1eb0.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250417/auto/storage/goog4_request%26X-Goog-Date%3D20250417T044559Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7545bfb37f2f14b5dde530ad76e4ced2753a2f1450d7f19bf41a6993b65230ed869db234ca7f4ac52a8241d64005c90a6108dbf36c1fc2986b234309505e555e7009eab9fe2b3340ee59fc59348dbf3d6f655c76a098582bb3128764c8d29e604514906926cdd9735e7b2c22bedbc27613d744e72f4eb4150e7716532db389c1acac8ae9e699a820d91b4f3c1b384fbc8aff06bc9d61175d5ad5a47ff153b9846129a9999a65c0bd751403f4aba82cb06fe0d47e8f6d40ae686f6666fdd02f20c29fb3aff8eba5c71b1d34831bd2549ee4cdd77730ee8ef845337db06ef4c64cce80238885f8a4a948b47185af4825d9f7307de17f5fd00707aa590d7b1e51c7
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fpdf import FPDF
import os

# Load the synthetic ECMS dataset
df = pd.read_csv("/content/ecms_maturity_audit_data.csv")

st.set_page_config(page_title="ECMS Maturity Audit Dashboard", layout="wide")
st.title("🌱 Environmental Compliance Maturity Audit Dashboard")

# Sidebar filter
industry = st.sidebar.selectbox("Select Industry to Review:", df["Industry"].unique())
selected = df[df["Industry"] == industry].squeeze()

# Summary Metrics
st.subheader(f"📊 Audit Summary for {industry}")
st.metric("Maturity Level", selected["EMS_Maturity_Level"])
st.metric("Compliance Outcome", selected["Compliance_Outcome"])

col1, col2 = st.columns(2)
with col1:
    st.write("### Key Compliance Features")
    st.write(f"- **ISO 14001 Certified:** {selected['Has_ISO14001_Certification']}")
    st.write(f"- **Leadership Commitment:** {selected['Leadership_Commitment']}")
    st.write(f"- **Supplier Engagement:** {selected['Supplier_Engagement']}")
    st.write(f"- **GHG Tracking:** {selected['GHG_Tracking']}")
    st.write(f"- **KPI Measurement:** {selected['KPI_Measurement']}")
    st.write(f"- **Corrective Actions:** {selected['Corrective_Actions']}")
    st.write(f"- **Public Environmental Report:** {selected['Public_Environmental_Report']}")

with col2:
    st.write("### Compliance Radar Chart")
    radar_labels = [
        "ISO 14001", "Leadership", "Suppliers", "GHG Tracking",
        "KPI Tracking", "Corrective Actions", "Reporting"
    ]
    radar_values = [
        selected['Has_ISO14001_Certification'] == "Yes",
        selected['Leadership_Commitment'] == "Strong",
        selected['Supplier_Engagement'] == "Yes",
        selected['GHG_Tracking'] == "Yes",
        selected['KPI_Measurement'] == "Yes",
        selected['Corrective_Actions'] == "Yes",
        selected['Public_Environmental_Report'] == "Yes"
    ]
    radar_numeric = [1 if v else 0 for v in radar_values]

    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))
    theta = [n / float(len(radar_labels)) * 2 * 3.14159 for n in range(len(radar_labels))]
    radar_numeric += radar_numeric[:1]
    theta += theta[:1]
    ax.plot(theta, radar_numeric, color='green', linewidth=2)
    ax.fill(theta, radar_numeric, color='lightgreen', alpha=0.25)
    ax.set_xticks(theta[:-1])
    ax.set_xticklabels(radar_labels)
    ax.set_yticklabels([])
    ax.set_title("Compliance Radar", size=16)
    st.pyplot(fig)

# Industry-wide comparison
st.divider()
st.subheader("📌 Industry Compliance Overview")
fig2, ax2 = plt.subplots(figsize=(10, 4))
sns.countplot(data=df, x="Compliance_Outcome", palette="Set2", order=["Laggard", "Compliant", "Leader"], ax=ax2)
ax2.set_title("Number of Industries by Compliance Outcome")
ax2.set_ylabel("Count")
st.pyplot(fig2)

# Export PDF Report
if st.button("📄 Export PDF Report"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=14)
    pdf.cell(200, 10, txt=f"ECMS Audit Report", ln=True, align='C')
    pdf.ln(5)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Industry: {industry}", ln=True)
    pdf.cell(200, 10, txt=f"Maturity Level: {selected['EMS_Maturity_Level']}", ln=True)
    pdf.cell(200, 10, txt=f"Compliance Outcome: {selected['Compliance_Outcome']}", ln=True)
    pdf.ln(5)
    pdf.cell(200, 10, txt=f"Key Features:", ln=True)
    for col in [
        "Has_ISO14001_Certification", "Leadership_Commitment", "Supplier_Engagement",
        "GHG_Tracking", "KPI_Measurement", "Corrective_Actions", "Public_Environmental_Report"
    ]:
        pdf.cell(200, 8, txt=f"{col.replace('_', ' ')}: {selected[col]}", ln=True)

    pdf_file = f"ECMS_Report_{industry.replace(' ', '_')}.pdf"
    pdf.output(pdf_file)

    with open(pdf_file, "rb") as f:
        st.download_button("📥 Download ECMS PDF Report", f, file_name=pdf_file)

# Downloadable version of dataset
st.download_button(
    label="📥 Download Full ECMS Dataset",
    data=df.to_csv(index=False),
    file_name="ecms_maturity_audit_data.csv",
    mime="text/csv"
)